### ISSUE TITLE
Problems of sketch not sending notification

### ISSUE THREAD

**Issue by rajbadri** [garthvh/esp8266button#73]
![internet-button](https://cloud.githubusercontent.com/assets/5882232/10915278/0e74793c-827c-11e5-91a0-b92b74fa8a78.jpg)
hi
i am using your sketch using the above schematic. it works but maybe 2 out of 10 times i don't get the ifttt notification.
your help will be appreciated.

Thanks

**Comment by garthvh** [comment]
I have some stand alone esp8266 chips now, I will try it using your sketch when I have some time

**Comment by niklasenB** [comment]
Hi, thanks for this great project! 
I have the same issue - it's sometimes simply not working and I don't know why.
I was digging into this debounce clause 

`// Debounce Button Presses
boolean debounce() {
  boolean retVal = false;
  int reading = digitalRead(BUTTON_PIN);
  if (reading != LAST_BUTTON_STATE) {
    LAST_DEBOUNCE_TIME = millis();    
  }
  if ((millis() - LAST_DEBOUNCE_TIME) > DEBOUNCE_DELAY) {
   if (reading != BUTTON_STATE) {
   BUTTON_STATE = reading;      
      if (BUTTON_STATE == HIGH) {
        retVal = true;
      }
    }
  }
  LAST_BUTTON_STATE = reading;
  return retVal;
}`

but no idea what can be the cause.
I have an ESP8266-01 using GPIO2, no LEDs (removed from the code) and connecting GPIO 2 to VCC through some resistor. Like 2-3 out of 10 times it's not working.

**Comment by JansZoro** [comment]
Hi garthvh , 

Have you leave the project? I'm trying to make it works, but I don't know if the present code needs a updating.

Thanks for your answer.

**Comment by garthvh** [comment]
I plan on pushing some changes pretty soon. I wrote it for a talk I gave on IOT, so it is not really in production anywhere.  I have not found a solution to the debounce issue, it only happens with ESP01 chips.

**Comment by JansZoro** [comment]
I made it work yesterday. Its a good project, I like it. I will prove the new features when you modify the code. I'm going to be attentive.

Thanks again.

**Comment by garthvh** [comment]
New github actions sketch is using new button debounce code
