### ISSUE TITLE
RGB LCD or LED?

### ISSUE THREAD

**Issue by Cribstone** [garthvh/esp8266button#74]
First off-Great job!  I've been looking to do something similar and thus far your project is the only one I've find that gives me a good template to work from.  One question I had is about the LED indicator.  In your documentation you reference an optional "RGB LCD" when by all appearances it looks like you are actually referring to an RGB LED...  Am I correct? Or should I be looking to include a LiquidCrystal library?

**Comment by garthvh** [comment]
You are correct, I thought I had fixed that everywhere, I might have re-introduced it with a new pull request.  Thanks for the heads up

**Comment by garthvh** [comment]
Fixed, thanks
